[package]
name = "one_billion_row_challenge_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
# used
memchr = "2.7.6"
memmap2 = "0.9.9"

# for testing
ahash = "0.8.12"
intmap = "3.1.3"
rustc-hash = "2.1.1"
smallvec = "1.15.1"

[profile.release]
lto="fat"
panic="abort"
debug = true
